#ifndef STATUS_H
#define STATUS_H
typedef enum { STATUS_OK=0, STATUS_BUSY, STATUS_TIMEOUT, STATUS_INVALID_ARGUMENT, STATUS_NO_SPACE, STATUS_CRC_ERROR, STATUS_IO_ERROR, STATUS_NOT_FOUND, STATUS_UNSUPPORTED, STATUS_CORRUPT } status_t;
#endif
